version: '3.7'
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    build: ./kibana
    container_name: kibana
    depends_on :
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet

  logstash:
    build: ./logstash
    container_name: logstash
    networks:
      - esnet

volumes:
  esdata01:
    driver: local

networks:
  esnet: